FROM docker.io/node:20
WORKDIR /app
COPY . .
WORKDIR /app/scraper-manzana
RUN npx pnpm install --filter=scraper-manzana

RUN npx pnpm build \
 && cp -r dbs/* dist/

RUN apt-get update && apt-get install -y tini sqlite3
ENTRYPOINT ["tini", "--"]
RUN echo '#!/bin/sh\nexec node /app/scraper-manzana/dist/cli.js "$@"' > /usr/local/bin/cli \
 && chmod +x /usr/local/bin/cli

ENV NODE_ENV=production
ENV DBS_PATH=/db
VOLUME /db

CMD ["cli", "cron"]
