# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'milei-twitter'
primary_region = 'eze'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'

[mounts]
  source="milei_twitter_db"
  destination="/db"

[build]
  dockerfile = "Dockerfile.sitio"
