# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'milei-twitter'
primary_region = 'eze'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source="milei_twitter_db"
  destination="/db"

[build]
  dockerfile = "Dockerfile.sitio"

[env]
  S3_BUCKET = "milei-twitter-db"
  S3_PATH = "db-fly"