export type TwitterCompatTweet = {
  __raw_UNSTABLE?: unknown;
  bookmarkCount?: number;
  conversationId?: string;
  hashtags: string[];
  html?: string;
  id?: string;
  inReplyToStatus?: TwitterCompatTweet;
  inReplyToStatusId?: string;
  isEdited?: boolean;
  versions?: string[];
  isQuoted?: boolean;
  isPin?: boolean;
  isReply?: boolean;
  isRetweet?: boolean;
  likes?: number;
  name?: string;
  mentions: Array<{ id: string; username?: string; name?: string }>;
  permanentUrl?: string;
  photos: Array<{ id: string; url: string; alt_text?: string }>;
  place?: unknown;
  quotedStatus?: TwitterCompatTweet;
  quotedStatusId?: string;
  replies?: number;
  retweets?: number;
  retweetedStatus?: TwitterCompatTweet;
  retweetedStatusId?: string;
  text?: string;
  thread: TwitterCompatTweet[];
  timeParsed?: Date;
  timestamp?: number;
  urls: string[];
  userId?: string;
  username?: string;
  videos: Array<{ id: string; preview: string; url?: string }>;
  views?: number;
  sensitiveContent?: boolean;
};
