services:
  scraper:
    build:
      context: ../..
      dockerfile: docker/scraper-manzana.Dockerfile
    image: milei-twitter-scraper:latest
    restart: unless-stopped
    env_file: .env.production
    environment:
      API_URL: ${API_URL:-https://milei.nulo.lol}
