name: Deploy to Trigger.dev (prod)

on:
  push:
    branches:
      - master
    paths:
      - "scraper-manzana/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        working-directory: scraper-manzana
        run: pnpm install

      - name: 🚀 Deploy Trigger.dev
        working-directory: scraper-manzana
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          pnpm run deploy:trigger-prod
